export type Locale = "zh" | "en";

export const siteContent = {
  zh: {
    navigation: [
      { href: "signal", label: "訊號" },
      { href: "experience", label: "體驗" },
      { href: "world", label: "視覺世界" },
      { href: "faq", label: "常見問題" },
    ],
    header: { homeLabel: "Qiddiya 奇地亞首頁", register: "預先登記", receive: "接收活動訊號", open: "開啟選單", close: "關閉選單", navLabel: "主要導覽", mobileNavLabel: "手機導覽" },
    hero: {
      alt: "光纖結構的巨型未來鯨魚，懸浮於台北城市上空",
      status: "SIGNAL STATUS",
      comingSoon: "COMING SOON",
      presentedBy: "TIANYEN PRESENTS",
      chineseName: "奇地亞",
      eventName: "未來光影音樂派對",
      tagline: "城市，進入下一個頻率。",
      register: "接收活動訊號",
      explore: "探索體驗",
      venue: "FIRST VENUE PARTNER",
    },
    principlesLabel: "主題核心",
    principles: [
      { title: "FUTURE CITY", label: "未來城市" },
      { title: "ECO AVANT-GARDE", label: "永續前衛" },
      { title: "FANTASY IMAGINATION", label: "奇幻創想" },
    ],
    manifesto: {
      eyebrow: "A NEW URBAN FREQUENCY",
      title: ["這不是一場派對。", "這是一座城市短暫醒來的方式。"],
      copy: "Qiddiya 奇地亞以光影為語言、電子音樂為脈衝、場域為身體，將水岸、建築與群眾編入同一個即時感知系統。我們把永續議題從說明文字中釋放，轉化為可穿越、可共振、也值得被分享的前衛體驗。",
    },
    journey: {
      eyebrow: "FIVE-ACT FREQUENCY JOURNEY",
      title: "五幕，進入奇地亞",
      intro: "音樂、光影、場域與群眾共同構成一條從城市現實走向未來想像的感官路徑。",
      chapters: [
        { title: "城市異常", english: "ANOMALY", copy: "熟悉的城市表面開始偏移。光沿著建築、水岸與人群流動，揭開另一層感知介面。" },
        { title: "污染顯影", english: "REVEAL", copy: "原本不可見的環境訊號被光雕轉譯，讓工業痕跡成為可被看見、討論與重新想像的城市記憶。" },
        { title: "鯨體甦醒", english: "AWAKEN", copy: "巨型生物光體穿越城市天際線，連結河堤、場域與台北的共同視野。" },
        { title: "能量共振", english: "RESONANCE", copy: "電子音樂、即時影像與群眾反應同步，現場不只是被觀看，而是共同生成。" },
        { title: "新地景生成", english: "REGENERATE", copy: "裝置、內容與社群留下可持續擴張的模組，讓一次派對成為下一座未來城市的原型。" },
      ],
    },
    scenes: [
      {
        code: "WORLD / 001",
        image: "contamination-corridor.jpg",
        alt: "以投影映出工業污染資料的沉浸式光影廊道",
        eyebrow: "THE INVISIBLE BECOMES VISIBLE",
        title: ["讓城市看見", "原本看不見的事。"],
        copy: "水門、河堤與工業地景不再只是背景。污染數據化為光的紋理，觀眾走進現場，也走進環境變化留下的痕跡。",
        tags: ["DATA PROJECTION", "URBAN MEMORY", "LIVE VISUAL"],
      },
      {
        code: "WORLD / 002",
        image: "energy-core.jpg",
        alt: "電子音樂舞台中心發光的生物能量核心裝置",
        eyebrow: "SOUND BECOMES ARCHITECTURE",
        title: ["聲音不是配樂。", "它是空間的骨架。"],
        copy: "電子音樂的頻率驅動光雕、裝置與即時視覺。每一段節奏都改變場域狀態，讓舞池成為持續生成的未來建築。",
        tags: ["ELECTRONIC MUSIC", "REAL-TIME SIGNAL", "COLLECTIVE ENERGY"],
      },
      {
        code: "WORLD / 003",
        image: "eco-avant-garde.jpg",
        alt: "結合植物形態與透明未來材質的永續裝置藝術",
        eyebrow: "ECOLOGY AS A FUTURE AESTHETIC",
        title: ["永續不是口號。", "它是新的感官語言。"],
        copy: "從模組化裝置、循環材料到可延展的內容系統，Qiddiya 將環境意識轉譯成令人著迷的未來美學。",
        tags: ["MODULAR SYSTEM", "CIRCULAR MATERIAL", "BIOFUTURE"],
      },
    ],
    experienceTagsLabel: "體驗元素",
    system: {
      alt: "可重組與延伸的未來光影裝置模組",
      eyebrow: "AN EXPANDING CULTURAL IP",
      title: "從一晚活動，長成一套可移動的未來系統。",
      copy: "首場由 TianYen 發起，MClub 作為首場合作場域。未來可依不同城市、建築與環境議題持續重組，延伸為系列活動、裝置展演、品牌共創與城市夜遊內容。",
      specs: ["場域共創", "品牌聯名", "裝置巡迴", "內容再傳播"],
    },
    cta: {
      alt: "未來城市夜景中的高端沉浸式光影音樂空間",
      eyebrow: "FIRST SIGNAL ACCESS",
      title: "接收第一道訊號。",
      copy: "預先登記首場活動資訊、優先名單與限定體驗公告。登記不等同取得入場資格，正式辦法將另行通知。",
      button: "預先登記",
    },
    faq: {
      eyebrow: "SIGNAL NOTES",
      title: "常見問題",
      items: [
        { question: "活動日期與地點確定了嗎？", answer: "目前為首波預告階段，日期與完整場域資訊將於正式公告時同步通知登記者。" },
        { question: "完成登記就能入場嗎？", answer: "預先登記代表加入優先通知名單，不等同門票或保證入場。正式票務與入場辦法將另行公布。" },
        { question: "Qiddiya 奇地亞由誰發起？", answer: "活動由光影品牌 TianYen 發起，MClub 為首場合作場域。" },
      ],
    },
    footer: { receive: "接收訊號", privacy: "隱私權", terms: "使用條款", legalLabel: "法律資訊" },
  },
  en: {
    navigation: [
      { href: "signal", label: "Signal" },
      { href: "experience", label: "Experience" },
      { href: "world", label: "Visual World" },
      { href: "faq", label: "FAQ" },
    ],
    header: { homeLabel: "Qiddiya home", register: "Pre-register", receive: "Receive the signal", open: "Open menu", close: "Close menu", navLabel: "Primary navigation", mobileNavLabel: "Mobile navigation" },
    hero: {
      alt: "A monumental fiber-optic whale suspended above a futuristic Taipei skyline",
      status: "SIGNAL STATUS",
      comingSoon: "COMING SOON",
      presentedBy: "TIANYEN PRESENTS",
      chineseName: "奇地亞",
      eventName: "FUTURE LIGHT & MUSIC PARTY",
      tagline: "The city enters a new frequency.",
      register: "Receive the signal",
      explore: "Explore the experience",
      venue: "FIRST VENUE PARTNER",
    },
    principlesLabel: "Core themes",
    principles: [
      { title: "FUTURE CITY", label: "Future City" },
      { title: "ECO AVANT-GARDE", label: "Eco Avant-Garde" },
      { title: "FANTASY IMAGINATION", label: "Radical Imagination" },
    ],
    manifesto: {
      eyebrow: "A NEW URBAN FREQUENCY",
      title: ["This is not just a party.", "It is how a city briefly awakens."],
      copy: "Qiddiya speaks through light, pulses through electronic music, and inhabits the city as its body. Waterfronts, architecture and people become one responsive sensory system. Sustainability leaves the language of explanation and becomes an avant-garde experience to enter, resonate with and share.",
    },
    journey: {
      eyebrow: "FIVE-ACT FREQUENCY JOURNEY",
      title: "Five acts into Qiddiya",
      intro: "Music, light, place and collective energy form a sensory passage from the city we know to the future we can imagine.",
      chapters: [
        { title: "Urban Anomaly", english: "ANOMALY", copy: "The familiar surface of the city begins to shift. Light moves through architecture, waterfronts and crowds, revealing another layer of perception." },
        { title: "Pollution Revealed", english: "REVEAL", copy: "Projection translates invisible environmental signals, turning industrial traces into urban memories that can be seen, discussed and reimagined." },
        { title: "The Whale Awakens", english: "AWAKEN", copy: "A monumental bioluminescent form crosses the skyline, connecting the riverbank, the venue and Taipei within one shared view." },
        { title: "Energy Resonance", english: "RESONANCE", copy: "Electronic music, real-time visuals and the crowd respond as one. The experience is not merely watched; it is collectively generated." },
        { title: "A New Landscape", english: "REGENERATE", copy: "Modular installations, content and community continue beyond one night, becoming a prototype for the next future city." },
      ],
    },
    scenes: [
      {
        code: "WORLD / 001",
        image: "contamination-corridor.jpg",
        alt: "An immersive light corridor visualizing industrial pollution data",
        eyebrow: "THE INVISIBLE BECOMES VISIBLE",
        title: ["Let the city see", "what was once invisible."],
        copy: "Floodgates, riverbanks and industrial landscapes are no longer background scenery. Pollution data becomes a texture of light, inviting visitors to enter the traces left by environmental change.",
        tags: ["DATA PROJECTION", "URBAN MEMORY", "LIVE VISUAL"],
      },
      {
        code: "WORLD / 002",
        image: "energy-core.jpg",
        alt: "A luminous bio-energy core at the center of an electronic music stage",
        eyebrow: "SOUND BECOMES ARCHITECTURE",
        title: ["Sound is not a score.", "It is the structure of space."],
        copy: "Electronic frequencies drive projection, installation and real-time visuals. Every rhythm changes the venue, turning the dance floor into an architecture that continuously regenerates.",
        tags: ["ELECTRONIC MUSIC", "REAL-TIME SIGNAL", "COLLECTIVE ENERGY"],
      },
      {
        code: "WORLD / 003",
        image: "eco-avant-garde.jpg",
        alt: "Sustainable installation art combining botanical forms with translucent future materials",
        eyebrow: "ECOLOGY AS A FUTURE AESTHETIC",
        title: ["Sustainability is not a slogan.", "It is a new sensory language."],
        copy: "From modular installations and circular materials to an expandable content system, Qiddiya translates environmental awareness into a compelling future aesthetic.",
        tags: ["MODULAR SYSTEM", "CIRCULAR MATERIAL", "BIOFUTURE"],
      },
    ],
    experienceTagsLabel: "Experience elements",
    system: {
      alt: "A modular future light installation designed to be reconfigured and expanded",
      eyebrow: "AN EXPANDING CULTURAL IP",
      title: "One night becomes a future system that can move between cities.",
      copy: "Initiated by TianYen with MClub as the first venue partner, Qiddiya can be reconfigured around new cities, architecture and environmental questions, expanding into a series of events, art installations, brand collaborations and urban night journeys.",
      specs: ["Venue Co-creation", "Brand Collaboration", "Installation Touring", "Content Amplification"],
    },
    cta: {
      alt: "A premium immersive light and music environment overlooking a future city at night",
      eyebrow: "FIRST SIGNAL ACCESS",
      title: "Receive the first signal.",
      copy: "Pre-register for event updates, priority-list news and limited experience announcements. Registration does not guarantee admission; full details will be announced separately.",
      button: "Pre-register",
    },
    faq: {
      eyebrow: "SIGNAL NOTES",
      title: "Frequently asked questions",
      items: [
        { question: "Have the date and venue been confirmed?", answer: "Qiddiya is currently in its first announcement phase. Registered guests will receive the confirmed date and complete venue information when the official announcement is released." },
        { question: "Does registration guarantee admission?", answer: "Pre-registration adds you to the priority notification list. It is not a ticket and does not guarantee entry. Ticketing and admission details will be announced separately." },
        { question: "Who initiated Qiddiya?", answer: "Qiddiya is initiated by the light-art brand TianYen, with MClub as the first venue partner." },
      ],
    },
    footer: { receive: "Receive the signal", privacy: "Privacy", terms: "Terms", legalLabel: "Legal information" },
  },
} as const;

export function localePath(locale: Locale, path = "") {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return locale === "en" ? `/en${normalized === "/" ? "" : normalized}` : normalized;
}
